### ISSUE TITLE
Hydration mismatch: incorrect number of rendered nodes.

### ISSUE THREAD

**Issue by ivanovivelin** [salesforce/lwc-webpack-plugin#13] opened 2022-09-01 15:46 UTC
Hi,

I am seeing the following error while running a sample LWC off-platform.

```
Error: [LWC error]: Hydration mismatch: incorrect number of rendered nodes. Client produced more nodes than the server.
```
```
import Sample from 'c/sample';

const availableFeature = detectFeatures();
const isCompatibleBrowser = Object.keys(availableFeature).some(
    feature => !availableFeature[feature]
);

if (isCompatibleBrowser) {
    unsupportedErrorMessage(availableFeature);
} else {
     customElements.define('c-omni', Sample.CustomElementConstructor);
}
```

I am using lwc-webpack-plugin 3.0.1

Empty / Sample LWC

```
import { LightningElement } from "lwc";

export default class Sample extends LightningElement {
    
}
```

**Comment by nolanlawson** [comment] 2022-09-01 16:05
Hi @ivanovivelin, I assume your HTML looks like this?

```html
<c-omni></c-omni>
```

In that case, I think this is a duplicate of https://github.com/salesforce/lwc/issues/2939

Currently our hydration logic assumes that any Server Side Rendered HTML will include the contents of the custom element, but everyone is using custom elements that way. Having an option to disable the mismatch errors would solve the issue for you.

Closing as this is not an issue with `lwc-webpack-plugin` but with `lwc` itself. Please reopen if I've misdiagnosed!

**Closed by nolanlawson** 2022-09-01 16:05 UTC
